A_split: False
a_fold: 100
bpr_batch: 2048
decay: 0.005
lr: 0.001
layer: 3
ssl_ratio: 0.1
ssl_reg: 0.1
ssl_temp: 0.2
ssl_aug_type: "ED"
seed: 42
dataset: "yelp2018"
topks: "[1,3,9]"
recdim: 64
dropout: 0
keepprob: 0.6
testbatch: 5
path: "./checkpoints"
tensorboard: 1
comment: "lgn"
load: 0
epochs: 100
multicore: 1
cores: 20
pretrain: 0
model: "lgn"
wandb: 0
wandb_name: "LightGCN"
